import bcrypt from 'bcryptjs';

const data = {
  users: [{
      name: 'Michelle',
      email: 'admin@example.com',
      company: 'Nuance',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'Molly',
      email: 'user@example.com',
      company: "Nuance",
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [{
      name: 'Blue Cut End Pocket Mop',
      system: 'Sealed Bucket (Pretreat) System',
      image: '/images/NFPM18BLEA.jpg',
      price: 5.67,
      msrp: 11.33,
      code: 'NFPM18BLEA',
      // rating: 4.5,
      dimension: '18"x15"x6',
      caseqty: 36,
      weight: 14,
      type: "Mops / Cloths / Pads",
      countInStock: 20,
      description: '18" Blue Pocket Mop color-coded Blue for General Purpose Cleaning. Constructed using corn rows for better cleaning and cut ends on fringe for better cleaning in corners. Launderable over 500 times. Features include: cut end pocket mops, bonded yarn, 4 center rows, durable blue H/D pocket back, and cut end Fringe.',
      dupsystem: ''
    },

    {
      name: 'Green Cut End Pocket Mop',
      system: 'Sealed Bucket (Pretreat) System',
      image: '/images/NFPM18GRE.jpg',
      price: 5.67,
      msrp: 11.33,
      code: 'NFPM18GREA',
      // rating: 4.5,
      dimension: '18"x15"x6',
      caseqty: 36,
      weight: 14,
      type: "Mops / Cloths / Pads",
      countInStock: 20,
      description: '18" Green Pocket Mop color-coded Green for cleaning in Food Service areas. Constructed using corn rows for better cleaning and cut ends on fringe for better cleaning in corners. Launderable over 500 times. Features include: cut end pocket mops, bonded yarn, 4 center rows, durable green H/D pocket back, and cut end Fringe.',
      dupsystem: ''
    },


    {
      name: 'Red Cut End Pocket Mop',
      system: 'Sealed Bucket (Pretreat) System',
      image: '/images/NFPM18RDEA.jpg',
      price: 5.67,
      msrp: 11.33,
      code: 'NFPM18RDEA',
      // rating: 4.5,
      dimension: '18"x15"x6',
      caseqty: 36,
      weight: 14,
      type: "Mops / Cloths / Pads",
      countInStock: 20,
      description: '18" Red Pocket Mop color-coded Red for cleaning in Critical Touch Point areas. Constructed using corn rows for better cleaning and cut ends on fringe for better cleaning in corners. Launderable over 500 times. Features include: cut end pocket mops, bonded yarn, 4 center rows, durable red H/D pocket back, and cut end Fringe.',
      dupsystem: '',
    },

    {
      name: 'Yellow Cut End Pocket Mop',
      system: 'Sealed Bucket (Pretreat) System',
      image: '/images/NFPM18YLEA.jpg',
      price: 5.67,
      msrp: 11.33,
      code: 'NFPM18YLEA',
      // rating: 4.5,
      dimension: '18"x15"x6',
      caseqty: 36,
      weight: 14,
      type: "Mops / Cloths / Pads",
      countInStock: 20,
      description: '18" Pocket Mop color-coded Yellow. Constructed using corn rows for better cleaning and cut ends on fringe for better cleaning in corners. Launderable over 500 times. Features include: cut end pocket mops, bonded yarn, 4 center rows, durable red H/D pocket back, and cut end Fringe.',
      dupsystem: '',
    },

    {
      name: 'Low Nap Blue Special Project Pocket Mop',
      system: 'Sealed Bucket (Pretreat) System',
      image: '/images/NFMF-PKT.jpg',
      price: 3.62,
      msrp: 7.25,
      code: 'NFMF-PKT',
      // rating: 4.5,
      dimension: '18"x15"x6',
      caseqty: 50,
      weight: 14,
      type: "Mops / Cloths / Pads",
      countInStock: 20,
      description: 'Economical low nap blue yarn pocket mop with gray pocket backing',
      dupsystem: '',
    },

    {
      name: "Long Loop L/L White Pocket Finish Mop",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFPM18WHEA.jpg",
      price: 5.67,
      msrp: 11.33,
      code: "NFPM18WHEA",
      dimension: '21"x14"x9"',
      caseqty: 36,
      weight: 15,
      type: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Long loop L/L white pocket fin mop wit mesh back and preconditioned white microfiber yarn ",
      dupsystem: ''
    },
    {
      name: "Blue Pocket Scrubber Mop",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFSCRUB-IT-PKT.jpg",
      price: 4.54,
      msrp: 9.09,
      code: "NFSCRUB-IT-PKT",
      dimension: '21"x14"x9"',
      caseqty: 36,
      weight: 15,
      type: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Pocket Scrubber mop with built in scrubber strips for hard to clean floors",
      dupsystem: ''
    },
    {
      name: '18" White Pocket Cleaning Mop',
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFPKT-WHT.jpg",
      price: 5.92,
      msrp: 11.84,
      code: "NFPKT-WHT",
      dimension: '18"x5"x6"',
      caseqty: 36,
      weight: 14,
      type: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "18",
      dupsystem: ''
    },
    {
      name: "Blue 6 Gallon Mop Bucket with Lid",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFSB06BLEA.jpg",
      price: 20.13,
      msrp: 40.25,
      code: "NFSB06BLEA",
      dimension: "26x13x23",
      caseqty: 5,
      weight: 18,
      type: "Buckets",
      countInStock: 20,
      description: "6 gallon sealed bucket for charging flat mops. Capacity up to 30 pocket mops per charge. Array mops in bucket, charge them. Seal bucket with sealer lid and turn over. After a few minutes, turn upright and begin to clean using wet, but not dripping mops. ",
      dupsystem: ''
    },
    {
      name: "Four Pack Caster Set",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFSB6-CASTER.jpg",
      price: 9.20,
      msrp: 18.40,
      code: "NFSB6-CASTER",
      dimension: "N/A",
      caseqty: 4,
      weight: 0,
      type: "Replacements / Accessories",
      countInStock: 20,
      description: "4 pack caster set for the 6 gallon mop bucket",
      dupsystem: ''
    },
    {
      name: "Gray 6 Gallon Mop Bucket with Lid",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFCTSBGYEA.jpg",
      price: 20.13,
      msrp: 40.25,
      code: "NFCTSBGYEA",
      dimension: "26x13x23",
      caseqty: 5,
      weight: 18,
      type: "Buckets",
      countInStock: 20,
      description: "6 gallon sealed bucket for charging flat mops. Capacity up to 30 pocket mops per charge. Array mops in bucket, charge them. Seal bucket with sealer lid and turn over. After a few minutes, turn upright and begin to clean using wet, but not dripping mops. ",
      dupsystem: ''
    },
    {
      name: "Replacement Lid for Blue 6 Gallon Sealed Bucket",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFSB-LID6.jpg",
      price: 11.44,
      msrp: 22.89,
      code: "NFSB-LID6",
      dimension: "N/A",
      caseqty: 1,
      weight: 1,
      type: "Replacements / Accessories",
      countInStock: 20,
      description: "Blue Lid for SB6BLU (Lid Only)",
      dupsystem: ''
    },
    {
      name: "Narrow Blue 6 Gallon Mop Bucket with Lid",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFS-19005.jpg",
      price: 19.15,
      msrp: 38.30,
      code: "NFS-19005",
      dimension: "26x13x23",
      caseqty: 5,
      weight: 18,
      type: "Buckets",
      countInStock: 20,
      description: "Small bucket to measure proper quantity of cleaning solution to add to sealed bucket for charging flat mops. Bucket is narrower so mops stay in place when bucket is flipped. It also has measuring lines, and a convenient handle for pouring and transport",
      dupsystem: ''
    },
    {
      name: "Narrow Gray 6 Gallon Mop Bucket with Lid",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFS-19004.jpg",
      price: 19.15,
      msrp: 38.30,
      code: "NFS-19004",
      dimension: "26x13x23",
      caseqty: 5,
      weight: 18,
      type: "Buckets",
      countInStock: 20,
      description: "Small bucket to measure proper quantity of cleaning solution to add to sealed bucket for charging flat mops. Bucket is narrower so mops stay in place when bucket is flipped. It also has measuring lines, and a convenient handle for pouring and transport",
      dupsystem: ''
    },
    {
      name: "Blue 1.5 Gallon Chemical Mix Bucket",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFMB02BLEA.jpg",
      price: 6.50,
      msrp: 13.00,
      code: "NFMB02BLEA",
      dimension: "10x10x14",
      caseqty: 5,
      weight: 6,
      type: "Buckets",
      countInStock: 20,
      description: "Small bucket to measure proper quantity of cleaning solution to add to sealed bucket for charging flat mops. Bucket is narrower so mops stay in place when bucket is flipped. It also has measuring lines, and a convenient handle for pouring and transport",
      dupsystem: ""
    },
    {
      name: "Green 1.5 Gallon Chemical Mix Bucket",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFMB2G.jpg",
      price: 6.50,
      msrp: 13.00,
      code: "NFMB2G",
      dimension: "10x10x14",
      caseqty: 5,
      weight: 6,
      type: "Buckets",
      countInStock: 20,
      description: "Small bucket to measure proper quantity of cleaning solution to add to sealed bucket for charging flat mops. Bucket is narrower so mops stay in place when bucket is flipped. It also has measuring lines, and a convenient handle for pouring and transport",
      dupsystem: ""
    },
    {
      name: "Red 1.5 Gallon Chemical Mix Bucket",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFMB2R.jpg",
      price: 6.50,
      msrp: 13.00,
      code: "NFMB2R",
      dimension: "10x10x14",
      caseqty: 5,
      weight: 6,
      type: "Buckets",
      countInStock: 20,
      description: "Small bucket to measure proper quantity of cleaning solution to add to sealed bucket for charging flat mops. Bucket is narrower so mops stay in place when bucket is flipped. It also has measuring lines, and a convenient handle for pouring and transport",
      dupsystem: ""
    },
    {
      name: "Yellow 1.5 Gallon Chemical Mix Bucket",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFMB2Y.jpg",
      price: 6.50,
      msrp: 13.00,
      code: "NFMB2Y",
      dimension: "10x10x14",
      caseqty: 5,
      weight: 6,
      type: "Buckets",
      countInStock: 20,
      description: "Small bucket to measure proper quantity of cleaning solution to add to sealed bucket for charging flat mops. Bucket is narrower so mops stay in place when bucket is flipped. It also has measuring lines, and a convenient handle for pouring and transport",
      dupsystem: ""
    },
    {
      name: "Mix Bucket Lid Only",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFMB-LID.jpg",
      price: 4.54,
      msrp: 9.09,
      code: "NFMB-LID",
      dimension: '"6"x6"x2"',
      caseqty: 1,
      weight: 2,
      type: "Replacements / Accessories",
      countInStock: 20,
      description: "Replacement lid for the 1.5 gallon chemical mix buckets",
      dupsystem: ""
    },
    {
      name: "Blue  3 Gallon Pad Bucket with Lid",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFSB03BLEA.jpg",
      price: 10.93,
      msrp: 21.85,
      code: "NFSB03BLEA",
      dimension: "20x24x13",
      caseqty: 10,
      weight: 15,
      type: "Buckets",
      countInStock: 20,
      description: "Blue 3 gallon sealed bucket. ",
      dupsystem: ""
    },
    {
      name: "Gray 3 Gallon Pad Bucket with Lid",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFSB03GYEA.jpg",
      price: 10.93,
      msrp: 21.85,
      code: "NFSB03GYEA",
      dimension: "20x24x13",
      caseqty: 10,
      weight: 15,
      type: "Buckets",
      countInStock: 20,
      description: "Gray 3 gallon sealed bucket. ",
      dupsystem: ""
    },
    {
      name: "Pocket Mop Frame",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFPF18EA.jpg",
      price: 10.95,
      msrp: 21.89,
      code: "NFPF18EA",
      dimension: "9x18x12",
      caseqty: 10,
      weight: 14,
      type: "Frames / Handles",
      countInStock: 20,
      description: "Frame for Pocket Mops with swivel; hands-free pick up and removal of mops. Lightweight, secure connection with telescopic handle.",
      dupsystem: ""
    },
    {
      name: "Telescopic Mop Handle",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFTH40ALEA.jpg",
      price: 6.96,
      msrp: 13.91,
      code: "NFTH40ALEA",
      dimension: "4x40x6",
      caseqty: 10,
      weight: 7,
      type: "Frames / Handles",
      countInStock: 20,
      description: "Versatile lightweight aluminum telescopic handle that fits Pocket, Tab and Wall Wash frames. Can be adjusted to any operator height.",
      dupsystem: "Divided Bucket System"
    },
    {
      name: "18'' Low Nap Save Blue ''C'' Style Velcro",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFSAVE-18BLU.jpg",
      price: 1.87,
      msrp: 3.75,
      code: "NFSAVE-18BLU",
      dimension: "20''x10''x20''",
      caseqty: 100,
      weight: 25,
      type: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Economical Velcro wet mop. Color coded Blue for General Purpose Cleaning. Handles all the jobs, launderable.",
      dupsystem: ""
    },
    {
      name: "18'' Low Nap Save Green ''C'' Style Velcro",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFSAVE-18GRE.jpg",
      price: 1.87,
      msrp: 3.75,
      code: "NFSAVE-18GRE",
      dimension: "20''x10''x20''",
      caseqty: 100,
      weight: 25,
      type: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Economical Velcro wet mop. Color coded green. Handles all  jobs, launderable.",
      dupsystem: ""
    },
    {
      name: "18'' Low Nap Save Red ''C'' Style Velcro",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFSAVE-18RED.jpg",
      price: 1.87,
      msrp: 3.75,
      code: "NFSAVE-18RED",
      dimension: "20''x10''x20''",
      caseqty: 100,
      weight: 25,
      type: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Economical Velcro wet mop. Color coded red. Handles all  jobs, launderable.",
      dupsystem: ""
    },
    {
      name: "19'' Low Nap Blue ''C'' Style Velcro",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFWM19BUEA.jpg",
      price: 2.41,
      msrp: 4.82,
      code: "NFWM19BUEA",
      dimension: "20''x10''x20''",
      caseqty: 100,
      weight: 25,
      type: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Economical 19'' Velcro wet mop. Color coded blue. Handles all  jobs, launderable.",
      dupsystem: ""
    },
    {
      name: "White Velcro with Blue Stripe Rolled Edge",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFFIN-FLAT.jpg",
      price: 3.39,
      msrp: 6.78,
      code: "NFFIN-FLAT",
      dimension: "21''x14''x9''",
      caseqty: 36,
      weight: 15,
      type: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "White velcro with blue stripe rolled edge and thick microfiber cloth inner liner.",
      dupsystem: ""
    },
    {
      name: "19'' Low Nap Blue ''K'' Style Velcro w/Scrubber strips",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFWM19BLEA.jpg",
      price: 3.16,
      msrp: 6.31,
      code: "NFWM19BLEA",
      dimension: "18''x15''x6''",
      caseqty: 36,
      weight: 14,
      type: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "19'' Low Nap Blue ''K'' Style Velcro with horizontal scrubber strips",
      dupsystem: ""
    },
    {
      name: "19'' Blue Scrubber Cut Pile ''K''",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFSM-BLU.jpg",
      price: 2.62,
      msrp: 5.24,
      code: "NFSM-BLU",
      dimension: "18''x15''x6''",
      caseqty: 36,
      weight: 14,
      type: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Versatile color coded velcro flat mops designed with cut pile and firm backing to provide more soil absorption and easier use. Launderable and resilient. Color Coded Blue for General Purpose Cleaning",
      dupsystem: ""
    },
    {
      name: "19'' RedScrubber Cut Pile ''K''",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFSM-RED.jpg",
      price: 2.62,
      msrp: 5.24,
      code: "NFSM-RED",
      dimension: "18''x15''x6''",
      caseqty: 36,
      weight: 14,
      type: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Versatile color coded velcro flat mops designed with cut pile and firm backing to provide more soil absorption and easier use. Launderable and resilient. Color coded red for cleaning in critical care areas.",
      dupsystem: ""
    },
    {
      name: "19'' Green Scrubber Cut Pile ''K''",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFSM-GRE.jpg",
      price: 2.62,
      msrp: 5.24,
      code: "NFSM-GRE",
      dimension: "18''x15''x6''",
      caseqty: 36,
      weight: 14,
      type: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Versatile color coded velcro flat mops designed with cut pile and firm backing to provide more soil absorption and easier use. Launderable and resilient. Color coded green for exclusive use in Food Service areas.",
      dupsystem: ""
    },
    {
      name: "19'' Yellow Scrubber Cut Pile ''K''",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFSM-YEL.jpg",
      price: 2.62,
      msrp: 5.24,
      code: "NFSM-YEL",
      dimension: "18''x15''x6''",
      caseqty: 36,
      weight: 14,
      type: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Versatile color coded velcro flat mops designed with cut pile and firm backing to provide more soil absorption and easier use. Launderable and resilient.",
      dupsystem: ""
    },
    {
      name: "Orange Microfiber Mop with Blue Scrub Strips",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFORG-195.jpg",
      price: 3.58,
      msrp: 7.15,
      code: "NFORG-195",
      dimension: "20''x10''x10''",
      caseqty: 100,
      weight: 30,
      type: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Orange Microfiber Mop with Blue Scrub Strips",
      dupsystem: ""
    },
    {
      name: "19'' Fluffy White Microfiber 'K''",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFSHOW18VEL.jpg",
      price: 3.54,
      msrp: 7.08,
      code: "NFSHOW18VEL",
      dimension: "20''x6''x20''",
      caseqty: 50,
      weight: 20,
      type: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "19'' Fluffy White Microfiber 'K'' Style",
      dupsystem: ""
    },
    {
      name: "19'' Long Loop Blue Velcro ''K''",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFWMLL19BLEA.jpg",
      price: 4.23,
      msrp: 8.45,
      code: "NFWMLL19BLEA",
      dimension: "18''x15''x6''",
      caseqty: 36,
      weight: 14,
      type: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Versatile color coded velcro flat mop with long loops to reach uneven and difficult surfaces. The long loops provide better penetration of unevan floors, including grout line and dips. Launderable and resilient. Color coded blue for general purpose cleaning",
      dupsystem: ""
    },
    {
      name: "19'' Long Loop Green Velcro ''K''",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFWMLL19GREA.jpg",
      price: 4.23,
      msrp: 8.45,
      code: "NFWMLL19GREA",
      dimension: "18''x15''x6''",
      caseqty: 36,
      weight: 14,
      type: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Versatile color coded velcro flat mop with long loops to reach uneven and difficult surfaces. The long loops provide better penetration of unevan floors, including grout line and dips. Launderable and resilient. Color coded green for food service cleaning",
      dupsystem: ""
    },
    {
      name: "19'' Long Loop Red Velcro ''K''",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFWMLL19RDEA.jpg",
      price: 4.23,
      msrp: 8.45,
      code: "NFWMLL19RDEA",
      dimension: "18''x15''x6''",
      caseqty: 36,
      weight: 14,
      type: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Versatile color coded velcro flat mop with long loops to reach uneven and difficult surfaces. The long loops provide better penetration of unevan floors, including grout line and dips. Launderable and resilient. Color coded red for critical touch cleaning",
      dupsystem: ""
    },
    {
      name: "19''  White Velcro Loop mop",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFWMLL19WHEA.jpg",
      price: 4.54,
      msrp: 9.08,
      code: "NFWMLL19WHEA",
      dimension: "18''x15''x6''",
      caseqty: 36,
      weight: 14,
      type: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Versatile flat mop with long loops to reach uneven and difficult surfaces. The long loops provide better penetration of unevan floors, including grout line and dips. Launderable and resilient. Color coded red for critical touch cleaning",
      dupsystem: ""
    }
  ]



};
export default data;