import bcrypt from 'bcryptjs';

const data = {
  users: [{
      name: 'Michelle',
      email: 'admin@example.com',
      company: 'Nuance',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'Molly',
      email: 'user@example.com',
      company: "Nuance",
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [{
      name: 'Blue Cut End Pocket Mop',
      system: 'Sealed Bucket (Pretreat) System',
      image: '/images/NFPM18BLEA.jpg',
      price: 5.67,
      msrp: 11.33,
      code: 'NFPM18BLEA',
      // rating: 4.5,
      dimension: '18"x15"x6',
      caseqty: 36,
      weight: 14,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: '18" Blue Pocket Mop color-coded Blue for General Purpose Cleaning. Constructed using corn rows for better cleaning and cut ends on fringe for better cleaning in corners. Launderable over 500 times. Features include: cut end pocket mops, bonded yarn, 4 center rows, durable blue H/D pocket back, and cut end Fringe.',
      dupsystem: ''
    },

    {
      name: 'Green Cut End Pocket Mop',
      system: 'Sealed Bucket (Pretreat) System',
      image: '/images/NFPM18GRE.jpg',
      price: 5.67,
      msrp: 11.33,
      code: 'NFPM18GREA',
      // rating: 4.5,
      dimension: '18"x15"x6',
      caseqty: 36,
      weight: 14,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: '18" Green Pocket Mop color-coded Green for cleaning in Food Service areas. Constructed using corn rows for better cleaning and cut ends on fringe for better cleaning in corners. Launderable over 500 times. Features include: cut end pocket mops, bonded yarn, 4 center rows, durable green H/D pocket back, and cut end Fringe.',
      dupsystem: ''
    },


    {
      name: 'Red Cut End Pocket Mop',
      system: 'Sealed Bucket (Pretreat) System',
      image: '/images/NFPM18RDEA.jpg',
      price: 5.67,
      msrp: 11.33,
      code: 'NFPM18RDEA',
      // rating: 4.5,
      dimension: '18"x15"x6',
      caseqty: 36,
      weight: 14,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: '18" Red Pocket Mop color-coded Red for cleaning in Critical Touch Point areas. Constructed using corn rows for better cleaning and cut ends on fringe for better cleaning in corners. Launderable over 500 times. Features include: cut end pocket mops, bonded yarn, 4 center rows, durable red H/D pocket back, and cut end Fringe.',
      dupsystem: '',
    },

    {
      name: 'Yellow Cut End Pocket Mop',
      system: 'Sealed Bucket (Pretreat) System',
      image: '/images/NFPM18YLEA.jpg',
      price: 5.67,
      msrp: 11.33,
      code: 'NFPM18YLEA',
      // rating: 4.5,
      dimension: '18"x15"x6',
      caseqty: 36,
      weight: 14,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: '18" Pocket Mop color-coded Yellow. Constructed using corn rows for better cleaning and cut ends on fringe for better cleaning in corners. Launderable over 500 times. Features include: cut end pocket mops, bonded yarn, 4 center rows, durable red H/D pocket back, and cut end Fringe.',
      dupsystem: '',
    },

    {
      name: 'Low Nap Blue Special Project Pocket Mop',
      system: 'Sealed Bucket (Pretreat) System',
      image: '/images/NFMF-PKT.jpg',
      price: 3.62,
      msrp: 7.25,
      code: 'NFMF-PKT',
      // rating: 4.5,
      dimension: '18"x15"x6',
      caseqty: 50,
      weight: 14,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: 'Economical low nap blue yarn pocket mop with gray pocket backing',
      dupsystem: '',
    },

    {
      name: "Long Loop L/L White Pocket Finish Mop",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFPM18WHEA.jpg",
      price: 5.67,
      msrp: 11.33,
      code: "NFPM18WHEA",
      dimension: '21"x14"x9"',
      caseqty: 36,
      weight: 15,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Long loop L/L white pocket fin mop wit mesh back and preconditioned white microfiber yarn ",
      dupsystem: ''
    },
    {
      name: "Blue Pocket Scrubber Mop",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFSCRUB-IT-PKT.jpg",
      price: 4.54,
      msrp: 9.09,
      code: "NFSCRUB-IT-PKT",
      dimension: '21"x14"x9"',
      caseqty: 36,
      weight: 15,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Pocket Scrubber mop with built in scrubber strips for hard to clean floors",
      dupsystem: ''
    },
    {
      name: '18" White Pocket Cleaning Mop',
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFPKT-WHT.jpg",
      price: 5.92,
      msrp: 11.84,
      code: "NFPKT-WHT",
      dimension: '18"x5"x6"',
      caseqty: 36,
      weight: 14,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "18",
      dupsystem: ''
    },
    {
      name: "Blue 6 Gallon Mop Bucket with Lid",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFSB06BLEA.jpg",
      price: 20.13,
      msrp: 40.25,
      code: "NFSB06BLEA",
      dimension: "26x13x23",
      caseqty: 5,
      weight: 18,
      producttype: "Buckets",
      countInStock: 20,
      description: "6 gallon sealed bucket for charging flat mops. Capacity up to 30 pocket mops per charge. Array mops in bucket, charge them. Seal bucket with sealer lid and turn over. After a few minutes, turn upright and begin to clean using wet, but not dripping mops. ",
      dupsystem: ''
    },
    {
      name: "Four Pack Caster Set",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFSB6-CASTER.jpg",
      price: 9.20,
      msrp: 18.40,
      code: "NFSB6-CASTER",
      dimension: "N/A",
      caseqty: 4,
      weight: 0,
      producttype: "Replacements / Accessories",
      countInStock: 20,
      description: "4 pack caster set for the 6 gallon mop bucket",
      dupsystem: ''
    },
    {
      name: "Gray 6 Gallon Mop Bucket with Lid",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFCTSBGYEA.jpg",
      price: 20.13,
      msrp: 40.25,
      code: "NFCTSBGYEA",
      dimension: "26x13x23",
      caseqty: 5,
      weight: 18,
      producttype: "Buckets",
      countInStock: 20,
      description: "6 gallon sealed bucket for charging flat mops. Capacity up to 30 pocket mops per charge. Array mops in bucket, charge them. Seal bucket with sealer lid and turn over. After a few minutes, turn upright and begin to clean using wet, but not dripping mops. ",
      dupsystem: ''
    },
    {
      name: "Replacement Lid for Blue 6 Gallon Sealed Bucket",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFSB-LID6.jpg",
      price: 11.44,
      msrp: 22.89,
      code: "NFSB-LID6",
      dimension: "N/A",
      caseqty: 1,
      weight: 1,
      producttype: "Replacements / Accessories",
      countInStock: 20,
      description: "Blue Lid for SB6BLU (Lid Only)",
      dupsystem: ''
    },
    {
      name: "Narrow Blue 6 Gallon Mop Bucket with Lid",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFS-19005.jpg",
      price: 19.15,
      msrp: 38.30,
      code: "NFS-19005",
      dimension: "26x13x23",
      caseqty: 5,
      weight: 18,
      producttype: "Buckets",
      countInStock: 20,
      description: "Small bucket to measure proper quantity of cleaning solution to add to sealed bucket for charging flat mops. Bucket is narrower so mops stay in place when bucket is flipped. It also has measuring lines, and a convenient handle for pouring and transport",
      dupsystem: ''
    },
    {
      name: "Narrow Gray 6 Gallon Mop Bucket with Lid",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFS-19004.jpg",
      price: 19.15,
      msrp: 38.30,
      code: "NFS-19004",
      dimension: "26x13x23",
      caseqty: 5,
      weight: 18,
      producttype: "Buckets",
      countInStock: 20,
      description: "Small bucket to measure proper quantity of cleaning solution to add to sealed bucket for charging flat mops. Bucket is narrower so mops stay in place when bucket is flipped. It also has measuring lines, and a convenient handle for pouring and transport",
      dupsystem: ''
    },
    {
      name: "Blue 1.5 Gallon Chemical Mix Bucket",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFMB02BLEA.jpg",
      price: 6.50,
      msrp: 13.00,
      code: "NFMB02BLEA",
      dimension: "10x10x14",
      caseqty: 5,
      weight: 6,
      producttype: "Buckets",
      countInStock: 20,
      description: "Small bucket to measure proper quantity of cleaning solution to add to sealed bucket for charging flat mops. Bucket is narrower so mops stay in place when bucket is flipped. It also has measuring lines, and a convenient handle for pouring and transport",
      dupsystem: ""
    },
    {
      name: "Green 1.5 Gallon Chemical Mix Bucket",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFMB2G.jpg",
      price: 6.50,
      msrp: 13.00,
      code: "NFMB2G",
      dimension: "10x10x14",
      caseqty: 5,
      weight: 6,
      producttype: "Buckets",
      countInStock: 20,
      description: "Small bucket to measure proper quantity of cleaning solution to add to sealed bucket for charging flat mops. Bucket is narrower so mops stay in place when bucket is flipped. It also has measuring lines, and a convenient handle for pouring and transport",
      dupsystem: ""
    },
    {
      name: "Red 1.5 Gallon Chemical Mix Bucket",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFMB2R.jpg",
      price: 6.50,
      msrp: 13.00,
      code: "NFMB2R",
      dimension: "10x10x14",
      caseqty: 5,
      weight: 6,
      producttype: "Buckets",
      countInStock: 20,
      description: "Small bucket to measure proper quantity of cleaning solution to add to sealed bucket for charging flat mops. Bucket is narrower so mops stay in place when bucket is flipped. It also has measuring lines, and a convenient handle for pouring and transport",
      dupsystem: ""
    },
    {
      name: "Yellow 1.5 Gallon Chemical Mix Bucket",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFMB2Y.jpg",
      price: 6.50,
      msrp: 13.00,
      code: "NFMB2Y",
      dimension: "10x10x14",
      caseqty: 5,
      weight: 6,
      producttype: "Buckets",
      countInStock: 20,
      description: "Small bucket to measure proper quantity of cleaning solution to add to sealed bucket for charging flat mops. Bucket is narrower so mops stay in place when bucket is flipped. It also has measuring lines, and a convenient handle for pouring and transport",
      dupsystem: ""
    },
    {
      name: "Mix Bucket Lid Only",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFMB-LID.jpg",
      price: 4.54,
      msrp: 9.09,
      code: "NFMB-LID",
      dimension: '"6"x6"x2"',
      caseqty: 1,
      weight: 2,
      producttype: "Replacements / Accessories",
      countInStock: 20,
      description: "Replacement lid for the 1.5 gallon chemical mix buckets",
      dupsystem: ""
    },
    {
      name: "Blue  3 Gallon Pad Bucket with Lid",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFSB03BLEA.jpg",
      price: 10.93,
      msrp: 21.85,
      code: "NFSB03BLEA",
      dimension: "20x24x13",
      caseqty: 10,
      weight: 15,
      producttype: "Buckets",
      countInStock: 20,
      description: "Blue 3 gallon sealed bucket. ",
      dupsystem: ""
    },
    {
      name: "Gray 3 Gallon Pad Bucket with Lid",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFSB03GYEA.jpg",
      price: 10.93,
      msrp: 21.85,
      code: "NFSB03GYEA",
      dimension: "20x24x13",
      caseqty: 10,
      weight: 15,
      producttype: "Buckets",
      countInStock: 20,
      description: "Gray 3 gallon sealed bucket. ",
      dupsystem: ""
    },
    {
      name: "Pocket Mop Frame",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFPF18EA.jpg",
      price: 10.95,
      msrp: 21.89,
      code: "NFPF18EA",
      dimension: "9x18x12",
      caseqty: 10,
      weight: 14,
      producttype: "Frames / Handles",
      countInStock: 20,
      description: "Frame for Pocket Mops with swivel; hands-free pick up and removal of mops. Lightweight, secure connection with telescopic handle.",
      dupsystem: ""
    },
    {
      name: "Telescopic Mop Handle",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFTH40ALEA.jpg",
      price: 6.96,
      msrp: 13.91,
      code: "NFTH40ALEA",
      dimension: "4x40x6",
      caseqty: 10,
      weight: 7,
      producttype: "Frames / Handles",
      countInStock: 20,
      description: "Versatile lightweight aluminum telescopic handle that fits Pocket, Tab and Wall Wash frames. Can be adjusted to any operator height.",
      dupsystem: "Divided Bucket System"
    },
    {
      name: "18'' Low Nap Save Blue ''C'' Style Velcro",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFSAVE-18BLU.jpg",
      price: 1.87,
      msrp: 3.75,
      code: "NFSAVE-18BLU",
      dimension: "20''x10''x20''",
      caseqty: 100,
      weight: 25,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Economical Velcro wet mop. Color coded Blue for General Purpose Cleaning. Handles all the jobs, launderable.",
      dupsystem: ""
    },
    {
      name: "18'' Low Nap Save Green ''C'' Style Velcro",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFSAVE-18GRE.jpg",
      price: 1.87,
      msrp: 3.75,
      code: "NFSAVE-18GRE",
      dimension: "20''x10''x20''",
      caseqty: 100,
      weight: 25,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Economical Velcro wet mop. Color coded green. Handles all  jobs, launderable.",
      dupsystem: ""
    },
    {
      name: "18'' Low Nap Save Red ''C'' Style Velcro",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFSAVE-18RED.jpg",
      price: 1.87,
      msrp: 3.75,
      code: "NFSAVE-18RED",
      dimension: "20''x10''x20''",
      caseqty: 100,
      weight: 25,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Economical Velcro wet mop. Color coded red. Handles all  jobs, launderable.",
      dupsystem: ""
    },
    {
      name: "19'' Low Nap Blue ''C'' Style Velcro",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFWM19BUEA.jpg",
      price: 2.41,
      msrp: 4.82,
      code: "NFWM19BUEA",
      dimension: "20''x10''x20''",
      caseqty: 100,
      weight: 25,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Economical 19'' Velcro wet mop. Color coded blue. Handles all  jobs, launderable.",
      dupsystem: ""
    },
    {
      name: "White Velcro with Blue Stripe Rolled Edge",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFFIN-FLAT.jpg",
      price: 3.39,
      msrp: 6.78,
      code: "NFFIN-FLAT",
      dimension: "21''x14''x9''",
      caseqty: 36,
      weight: 15,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "White velcro with blue stripe rolled edge and thick microfiber cloth inner liner.",
      dupsystem: ""
    },
    {
      name: "19'' Low Nap Blue ''K'' Style Velcro w/Scrubber strips",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFWM19BLEA.jpg",
      price: 3.16,
      msrp: 6.31,
      code: "NFWM19BLEA",
      dimension: "18''x15''x6''",
      caseqty: 36,
      weight: 14,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "19'' Low Nap Blue ''K'' Style Velcro with horizontal scrubber strips",
      dupsystem: ""
    },
    {
      name: "19'' Blue Scrubber Cut Pile ''K''",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFSM-BLU.jpg",
      price: 2.62,
      msrp: 5.24,
      code: "NFSM-BLU",
      dimension: "18''x15''x6''",
      caseqty: 36,
      weight: 14,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Versatile color coded velcro flat mops designed with cut pile and firm backing to provide more soil absorption and easier use. Launderable and resilient. Color Coded Blue for General Purpose Cleaning",
      dupsystem: ""
    },
    {
      name: "19'' RedScrubber Cut Pile ''K''",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFSM-RED.jpg",
      price: 2.62,
      msrp: 5.24,
      code: "NFSM-RED",
      dimension: "18''x15''x6''",
      caseqty: 36,
      weight: 14,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Versatile color coded velcro flat mops designed with cut pile and firm backing to provide more soil absorption and easier use. Launderable and resilient. Color coded red for cleaning in critical care areas.",
      dupsystem: ""
    },
    {
      name: "19'' Green Scrubber Cut Pile ''K''",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFSM-GRE.jpg",
      price: 2.62,
      msrp: 5.24,
      code: "NFSM-GRE",
      dimension: "18''x15''x6''",
      caseqty: 36,
      weight: 14,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Versatile color coded velcro flat mops designed with cut pile and firm backing to provide more soil absorption and easier use. Launderable and resilient. Color coded green for exclusive use in Food Service areas.",
      dupsystem: ""
    },
    {
      name: "19'' Yellow Scrubber Cut Pile ''K''",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFSM-YEL.jpg",
      price: 2.62,
      msrp: 5.24,
      code: "NFSM-YEL",
      dimension: "18''x15''x6''",
      caseqty: 36,
      weight: 14,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Versatile color coded velcro flat mops designed with cut pile and firm backing to provide more soil absorption and easier use. Launderable and resilient.",
      dupsystem: ""
    },
    {
      name: "Orange Microfiber Mop with Blue Scrub Strips",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFORG-195.jpg",
      price: 3.58,
      msrp: 7.15,
      code: "NFORG-195",
      dimension: "20''x10''x10''",
      caseqty: 100,
      weight: 30,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Orange Microfiber Mop with Blue Scrub Strips",
      dupsystem: ""
    },
    {
      name: "19'' Fluffy White Microfiber 'K''",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFSHOW18VEL.jpg",
      price: 3.54,
      msrp: 7.08,
      code: "NFSHOW18VEL",
      dimension: "20''x6''x20''",
      caseqty: 50,
      weight: 20,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "19'' Fluffy White Microfiber 'K'' Style",
      dupsystem: ""
    },
    {
      name: "19'' Long Loop Blue Velcro ''K''",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFWMLL19BLEA.jpg",
      price: 4.23,
      msrp: 8.45,
      code: "NFWMLL19BLEA",
      dimension: "18''x15''x6''",
      caseqty: 36,
      weight: 14,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Versatile color coded velcro flat mop with long loops to reach uneven and difficult surfaces. The long loops provide better penetration of unevan floors, including grout line and dips. Launderable and resilient. Color coded blue for general purpose cleaning",
      dupsystem: ""
    },
    {
      name: "19'' Long Loop Green Velcro ''K''",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFWMLL19GREA.jpg",
      price: 4.23,
      msrp: 8.45,
      code: "NFWMLL19GREA",
      dimension: "18''x15''x6''",
      caseqty: 36,
      weight: 14,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Versatile color coded velcro flat mop with long loops to reach uneven and difficult surfaces. The long loops provide better penetration of unevan floors, including grout line and dips. Launderable and resilient. Color coded green for food service cleaning",
      dupsystem: ""
    },
    {
      name: "19'' Long Loop Red Velcro ''K''",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFWMLL19RDEA.jpg",
      price: 4.23,
      msrp: 8.45,
      code: "NFWMLL19RDEA",
      dimension: "18''x15''x6''",
      caseqty: 36,
      weight: 14,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Versatile color coded velcro flat mop with long loops to reach uneven and difficult surfaces. The long loops provide better penetration of unevan floors, including grout line and dips. Launderable and resilient. Color coded red for critical touch cleaning",
      dupsystem: ""
    },
    {
      name: "19''  White Velcro Loop mop",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFWMLL19WHEA.jpg",
      price: 4.54,
      msrp: 9.08,
      code: "NFWMLL19WHEA",
      dimension: "18''x15''x6''",
      caseqty: 36,
      weight: 14,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Versatile flat mop with long loops to reach uneven and difficult surfaces. The long loops provide better penetration of unevan floors, including grout line and dips. Launderable and resilient. Color coded red for critical touch cleaning",
      dupsystem: ""
    },

    {
      name: "Small Metal Compact Cart on Casters",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFCTSBEA.jpg",
      price: 101.20,
      msrp: 202.40,
      code: "NFCTSBEA",
      dimension: "24x24x24''",
      caseqty: 1,
      weight: 15,
      producttype: "Carts",
      countInStock: 20,
      description: "NOW INCLUDES: Dirty Mop Basket,metal wire tool basket, \nblue 6-gallon sealed bucket.",
      dupsystem: ""
    },
    {
      name: "Replacement Metal Wire Tool Basket",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFCTWBEA.jpg",
      price: 10.93,
      msrp: 21.85,
      code: "NFCTWBEA",
      dimension: "8''x20''x8''",
      caseqty: 1,
      weight: 3,
      producttype: "Replacements / Accessories",
      countInStock: 20,
      description: "Replacement Basket for Small Metal Compact Cart on Casters",
      dupsystem: ""
    },
    {
      name: "Small compact cart with vinyl trash receptacle ",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFSBCTCDSS.jpg",
      price: 178.25,
      msrp: 356.50,
      code: "NFSBCTCDSS",
      dimension: "24x24x24''",
      caseqty: 1,
      weight: 25,
      producttype: "Carts",
      countInStock: 20,
      description: "Small compact cart with blue 6 gallon sealed bucket, gray 6 gallon sealed bucket, wire basket, and vinyl trash receptacle ",
      dupsystem: ""
    },
    {
      name: "Replacement Caster",
      system: "New and Miscellaneous Items",
      image: "/images/NFDB50-CASTER.jpg",
      price: 5.69,
      msrp: 11.39,
      code: "NFDB50-CASTER",
      dimension: "N/A",
      caseqty: 1,
      weight: 0,
      producttype: "Replacements / Accessories",
      countInStock: 20,
      description: "Replacement Caster for metal cart and divided bucket.",
      dupsystem: ""
    },
    {
      name: "Economy - Standard Maid Cart",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFCART-MAID.jpg",
      price: 86.90,
      msrp: 173.80,
      code: "NFCART-MAID",
      dimension: "N/A",
      caseqty: 1,
      weight: 0,
      producttype: "Carts",
      countInStock: 20,
      description: "Popular, well-designed cart that can be used everywhere.",
      dupsystem: ""
    },
    {
      name: "Replacement Yellow Vinyl Trash Bag",
      system: 'Sealed Bucket (Pretreat) System',
      image: "/images/NFCM-BAG-Y.jpg",
      price: 20.33,
      msrp: 40.66,
      code: "NFCM-BAG-Y",
      dimension: "N/A",
      caseqty: 1,
      weight: 0,
      producttype: "Replacements / Accessories",
      countInStock: 20,
      description: "Replacement Yellow Vinyl Trash Bag for compact cart.",
      dupsystem: ""
    },
    {
      name: "Grey Divided Bucket w/ Side Press Wringer",
      system: "Divided Bucket System",
      image: "/images/NFDBGY05SP.jpg",
      price: 82.80,
      msrp: 165.60,
      code: "NFDBGY05SP",
      dimension: "20''x22''x38''",
      caseqty: 1,
      weight: 20,
      producttype: "Buckets",
      countInStock: 20,
      description: "This divided bucket separates the cleaning solution separate from the dirty rinse water to prevent cross contamination and elimminates waste. Wringer included.",
      dupsystem: ""
    },
    {
      name: "Grey Divided Bucket Only",
      system: "Divided Bucket System",
      image: "/images/NFDB50-BUCKET-ONLY.jpg",
      price: 67.97,
      msrp: 135.94,
      code: "NFDB50-BUCKET-ONLY",
      dimension: "N/A",
      caseqty: 1,
      weight: 0,
      producttype: "Buckets",
      countInStock: 20,
      description: "This divided bucket separates the cleaning solution separate from the dirty rinse water to prevent cross contamination and elimminates waste.",
      dupsystem: ""
    },
    {
      name: "Divided Bucket w/ Down Press Wringer",
      system: "Divided Bucket System",
      image: "/images/NFDB05GYEA.jpg",
      price: 94.30,
      msrp: 188.60,
      code: "NFDB05GYEA",
      dimension: "20''x22''x38''",
      caseqty: 1,
      weight: 20,
      producttype: "Buckets",
      countInStock: 20,
      description: "This divided bucket separates the cleaning solution separate from the dirty rinse water to prevent cross contamination and elimminates waste.",
      dupsystem: ""
    },
    {
      name: "Divided Bucket w/ ROLLER WRINGER",
      system: "Divided Bucket System",
      image: "/images/NFROLLER-COMBO.jpg",
      price: 112.70,
      msrp: 225.40,
      code: "NFROLLER-COMBO",
      dimension: "20''x22''x38''",
      caseqty: 1,
      weight: 20,
      producttype: "Buckets",
      countInStock: 20,
      description: "This divided bucket separates the cleaning solution separate from the dirty rinse water to prevent cross contamination and elimminates waste.",
      dupsystem: ""
    },
    {
      name: "Roller Wringer for use w/tab style mops",
      system: "Divided Bucket System",
      image: "/images/NFROLLER-WRINGER.jpg",
      price: 97.75,
      msrp: 195.50,
      code: "NFROLLER-WRINGER",
      dimension: "12''x10''x16''",
      caseqty: 1,
      weight: 20,
      producttype: "Buckets",
      countInStock: 20,
      description: "This divided bucket separates the cleaning solution separate from the dirty rinse water to prevent cross contamination and elimminates waste.",
      dupsystem: ""
    },
    {
      name: "Blue Tab Mop",
      system: "Divided Bucket System",
      image: "/images/NFTM18BLEA.jpg",
      price: 5.35,
      msrp: 10.70,
      code: "NFTM18BLEA",
      dimension: "9''x21''x14''",
      caseqty: 36,
      weight: 15,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "18",
      dupsystem: ""
    },
    {
      name: "Green Tab Mop",
      system: "Divided Bucket System",
      image: "/images/NFTM18GREA.jpg",
      price: 5.35,
      msrp: 10.70,
      code: "NFTM18GREA",
      dimension: "9''x21''x14''",
      caseqty: 36,
      weight: 15,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "18",
      dupsystem: ""
    },
    {
      name: "Red Tab Mop",
      system: "Divided Bucket System",
      image: "/images/NFTM18RDEA.jpg",
      price: 5.35,
      msrp: 10.70,
      code: "NFTM18RDEA",
      dimension: "9''x21''x14''",
      caseqty: 36,
      weight: 15,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "18",
      dupsystem: ""
    },
    {
      name: "Yellow Tab Mop",
      system: "Divided Bucket System",
      image: "/images/NFTM18YLEA.jpg",
      price: 5.35,
      msrp: 10.70,
      code: "NFTM18YLEA",
      dimension: "9''x21''x14''",
      caseqty: 36,
      weight: 15,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Durable  - over 500 Launderings, Corn row construction for deeper cleaning, Able to be wrung out and re-used, Color-coded to prevent cross-contamination",
      dupsystem: ""
    },
    {
      name: "Gray/Black Step On Lock Tab Mop Frame",
      system: "Divided Bucket System",
      image: "/images/NFTF18BLEA.jpg",
      price: 14.89,
      msrp: 29.79,
      code: "NFTF18BLEA",
      dimension: "11''x16''x8''",
      caseqty: 10,
      weight: 13,
      producttype: "Frames / Handles",
      countInStock: 20,
      description: "Durable locking frame for  Tab Mops. Unique step on locking feature assures even tension on mop surface for better cleaning and secure hold. Swivel feature allows ease of use.",
      dupsystem: ""
    },

    {
      name: "Double Mop Buckets w/Side Press Wringer(Heavy Duty Metal Trolley)",
      system: "Double Bucket and Trolley Systems",
      image: "/images/NFTROLLEY1.jpg",
      price: 138.00,
      msrp: 276.00,
      code: "NFTROLLEY1",
      dimension: "16x31x18''",
      caseqty: 1,
      weight: 28,
      producttype: "Buckets",
      countInStock: 20,
      description: "Separating clean solutions fro dirty rinse water is critical to mopping any floor. Experience the newer, more effective and ergonomic way of mopping floors with the double bucket system.",
      dupsystem: ""
    },
    {
      name: "Replacement Casters for Metal Double Bucket Trolley",
      system: "Double Bucket and Trolley Systems",
      image: "/images/NFTROLLEY1-CASTERS.jpg",
      price: 28.75,
      msrp: 57.50,
      code: "NFTROLLEY1-CASTER",
      dimension: "N/A",
      caseqty: 4,
      weight: 0,
      producttype: "Replacements / Accessories",
      countInStock: 20,
      description: "Replacement casters for TROLLEY1",
      dupsystem: ""
    },
    {
      name: "Double Mop Buckets w/Down Press Wringer (Plastic Trolley)",
      system: "Double Bucket and Trolley Systems",
      image: "/images/NFDBT2GYEA.jpg",
      price: 132.25,
      msrp: 264.50,
      code: "NFDBT2GYEA",
      dimension: "16x31x18''",
      caseqty: 1,
      weight: 23,
      producttype: "Buckets",
      countInStock: 20,
      description: "Separating clean solutions fro dirty rinse water is critical to mopping any floor. Experience the newer, more effective and ergonomic way of mopping floors with the double bucket system.",
      dupsystem: ""
    },
    {
      name: "Double Bucket System w/Side Press Wringer (Plastic Trolley)",
      system: "Double Bucket and Trolley Systems",
      image: "/images/NFDBSPGYEA.jpg",
      price: 115.00,
      msrp: 230.00,
      code: "NFDBSPGYEA",
      dimension: "16x31x18''",
      caseqty: 1,
      weight: 23,
      producttype: "Buckets",
      countInStock: 20,
      description: "Separating clean solutions fro dirty rinse water is critical to mopping any floor. Experience the newer, more effective and ergonomic way of mopping floors with the double bucket system.",
      dupsystem: ""
    },
    {
      name: "Replacement Casters for Plastic Double Bucket Trolley",
      system: "Double Bucket and Trolley Systems",
      image: "/images/NFTROLLEY2-CASTER.jpg",
      price: 5.69,
      msrp: 11.38,
      code: "NFTROLLEY2-CASTER",
      dimension: "N/A",
      caseqty: 1,
      weight: 0,
      producttype: "Replacements / Accessories",
      countInStock: 20,
      description: "Replacement casters for NFDBT2GYEA",
      dupsystem: ""
    },
    {
      name: "Yellow Small Microfiber Tube Mop",
      system: "Double Bucket and Trolley Systems",
      image: "/images/NFSMYLEA.jpg",
      price: 5.78,
      msrp: 11.55,
      code: "NFSMYLEA",
      dimension: "10''x17''x14''",
      caseqty: 12,
      weight: 12,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Don't Settle For Cheap Cotton Alternatives! Microfiber soaks up far more liquid & picks up more dirt than cotton. Plus, our tube mops are extremely soft & won't fall apart or frizz like a traditional cotton string mops.",
      dupsystem: ""
    },
    {
      name: "Blue Medium Microfiber Tube Mop",
      system: "Double Bucket and Trolley Systems",
      image: "/images/NFSMBLEAMED.jpg",
      price: 6.33,
      msrp: 12.65,
      code: "NFSMBLEAMED",
      dimension: "10''x17''x14''",
      caseqty: 12,
      weight: 12,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Don't Settle For Cheap Cotton Alternatives! Microfiber soaks up far more liquid & picks up more dirt than cotton. Plus, our tube mops are extremely soft & won't fall apart or frizz like a traditional cotton string mops.",
      dupsystem: ""
    },
    {
      name: "Red Medium Microfiber Tube Mop",
      system: "Double Bucket and Trolley Systems",
      image: "/images/NFSMRDEA.jpg",
      price: 6.33,
      msrp: 12.65,
      code: "NFSMRDEA",
      dimension: "10''x17''x14''",
      caseqty: 12,
      weight: 12,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Don't Settle For Cheap Cotton Alternatives! Microfiber soaks up far more liquid & picks up more dirt than cotton. Plus, our tube mops are extremely soft & won't fall apart or frizz like a traditional cotton string mops.",
      dupsystem: ""
    },
    {
      name: "Green Medium Microfiber Tube Mop",
      system: "Double Bucket and Trolley Systems",
      image: "/images/NFSMGREA.jpg",
      price: 6.33,
      msrp: 12.65,
      code: "NFSMGREA",
      dimension: "10''x17''x14''",
      caseqty: 12,
      weight: 12,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Don't Settle For Cheap Cotton Alternatives! Microfiber soaks up far more liquid & picks up more dirt than cotton. Plus, our tube mops are extremely soft & won't fall apart or frizz like a traditional cotton string mops.",
      dupsystem: ""
    },
    {
      name: "Purple Medium Microfiber Tube Mop",
      system: "Double Bucket and Trolley Systems",
      image: "/images/NFMPUREA.jpg",
      price: 6.33,
      msrp: 12.65,
      code: "NFMPUREA",
      dimension: "10''x17''x14''",
      caseqty: 12,
      weight: 12,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Don't Settle For Cheap Cotton Alternatives! Microfiber soaks up far more liquid & picks up more dirt than cotton. Plus, our tube mops are extremely soft & won't fall apart or frizz like a traditional cotton string mops.",
      dupsystem: ""
    },
    {
      name: "Gray Medium Microfiber Mop with Rings",
      system: "Double Bucket and Trolley Systems",
      image: "/images/NFGRAY-MD.jpg",
      price: 6.55,
      msrp: 13.09,
      code: "NFGRAY-MD",
      dimension: "10''x17''x14''",
      caseqty: 12,
      weight: 12,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Don't Settle For Cheap Cotton Alternatives! Microfiber soaks up far more liquid & picks up more dirt than cotton. Plus, our tube mops are extremely soft & won't fall apart or frizz like a traditional cotton string mops.",
      dupsystem: ""
    },
    {
      name: "Blue Large Microfiber Tube Mop",
      system: "Double Bucket and Trolley Systems",
      image: "/images/NFSMBLEA.jpg",
      price: 6.88,
      msrp: 13.75,
      code: "NFSMBLEA",
      dimension: "10''x17''x14''",
      caseqty: 12,
      weight: 13,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Don't Settle For Cheap Cotton Alternatives! Microfiber soaks up far more liquid & picks up more dirt than cotton. Plus, our tube mops are extremely soft & won't fall apart or frizz like a traditional cotton string mops.",
      dupsystem: ""
    },
    {
      name: "Green Large Microfiber Tube Mop",
      system: "Double Bucket and Trolley Systems",
      image: "/images/NFGRE-LG.jpg",
      price: 6.88,
      msrp: 13.75,
      code: "NFGRE-LG",
      dimension: "10''x17''x14''",
      caseqty: 12,
      weight: 13,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Don't Settle For Cheap Cotton Alternatives! Microfiber soaks up far more liquid & picks up more dirt than cotton. Plus, our tube mops are extremely soft & won't fall apart or frizz like a traditional cotton string mops.",
      dupsystem: ""
    },
    {
      name: "White Large Tube Mop",
      system: "Double Bucket and Trolley Systems",
      image: "/images/NFSMWHEA.jpg",
      price: 6.88,
      msrp: 13.75,
      code: "NFSMWHEA",
      dimension: "10''x17''x14''",
      caseqty: 12,
      weight: 13,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Don't Settle For Cheap Cotton Alternatives! Microfiber soaks up far more liquid & picks up more dirt than cotton. Plus, our tube mops are extremely soft & won't fall apart or frizz like a traditional cotton string mops.",
      dupsystem: ""
    },
    {
      name: "Orange Extra Large Microfiber Tube Mop",
      system: "Double Bucket and Trolley Systems",
      image: "/images/NFSMOREA.jpg",
      price: 7.65,
      msrp: 15.29,
      code: "NFSMOREA",
      dimension: "10''x17''x14''",
      caseqty: 12,
      weight: 13,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Don't Settle For Cheap Cotton Alternatives! Microfiber soaks up far more liquid & picks up more dirt than cotton. Plus, our tube mops are extremely soft & won't fall apart or frizz like a traditional cotton string mops.",
      dupsystem: ""
    },
    {
      name: "Medium String Microfiber Mop",
      system: "Double Bucket and Trolley Systems",
      image: "/images/NFSTRING-BLU-18.jpg",
      price: 7.07,
      msrp: 14.15,
      code: "NFSTRING-BLU-18",
      dimension: "10''x17''x14''",
      caseqty: 12,
      weight: 13,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Don't Settle For Cheap Cotton Alternatives! Microfiber soaks up far more liquid & picks up more dirt than cotton. Plus, our tube mops are extremely soft & won't fall apart or frizz like a traditional cotton string mops.",
      dupsystem: ""
    },
    {
      name: "Large String Microfiber Mop",
      system: "Double Bucket and Trolley Systems",
      image: "/images/NFSTRING-BLU-24.jpg",
      price: 8.91,
      msrp: 17.83,
      code: "NFSTRING-BLU-24",
      dimension: "10''x17''x14''",
      caseqty: 12,
      weight: 13,
      producttype: "Mops / Cloths / Pads",
      countInStock: 20,
      description: "Don't Settle For Cheap Cotton Alternatives! Microfiber soaks up far more liquid & picks up more dirt than cotton. Plus, our tube mops are extremely soft & won't fall apart or frizz like a traditional cotton string mops.",
      dupsystem: ""
    },
    {
      name: "Jaw Style Mop Handle",
      system: "Double Bucket and Trolley Systems",
      image: "/images/NFJH40YLEA.jpg",
      price: 7.44,
      msrp: 14.87,
      code: "NFJH40YLEA",
      dimension: "64''x8''x8''",
      caseqty: 12,
      weight: 14,
      producttype: "Frames / Handles",
      countInStock: 20,
      description: "Handle for Tube Mops",
      dupsystem: ""
    },
    {
      name: "Red Jaw Style Mop Handle",
      system: "Double Bucket and Trolley Systems",
      image: "/images/NFRED-JAW.jpg",
      price: 7.44,
      msrp: 14.87,
      code: "NFRED-JAW",
      dimension: "64''x8''x8''",
      caseqty: 12,
      weight: 14,
      producttype: "Frames / Handles",
      countInStock: 20,
      description: "Handle for Tube Mops",
      dupsystem: ""
    }


  ]
};
export default data;